package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                = (*sequenceResource)(nil)
	_ resource.ResourceWithImportState = (*sequenceResource)(nil)
)

// NewSequenceResource manages one immutable sequence version.
func NewSequenceResource() resource.Resource { return &sequenceResource{} }

type sequenceResource struct{ base }

type sequenceModel struct {
	ID         types.String         `tfsdk:"id"`
	TenantID   types.String         `tfsdk:"tenant_id"`
	Namespace  types.String         `tfsdk:"namespace"`
	Name       types.String         `tfsdk:"name"`
	Version    types.Int64          `tfsdk:"version"`
	Definition jsontypes.Normalized `tfsdk:"definition"`
	Status     types.String         `tfsdk:"status"`
	Deprecated types.Bool           `tfsdk:"deprecated"`
	CreatedAt  types.String         `tfsdk:"created_at"`
	Warnings   types.List           `tfsdk:"warnings"`
}

// Keys owned by resource attributes or assigned by the provider; they may
// appear in `definition` only when they agree with the attributes.
var sequenceIdentityKeys = []string{"id", "tenant_id", "namespace", "name", "version", "created_at"}

func (r *sequenceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sequence"
}

func (r *sequenceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	replaceStr := []planmodifier.String{stringplanmodifier.RequiresReplace()}
	resp.Schema = schema.Schema{
		Description: "One version of an Orch8 sequence (workflow definition). Sequence versions are immutable in the engine " +
			"(`POST /sequences` creates, there is no update), so any change replaces the resource. To roll out a new " +
			"version without deleting the old one, create a second `orch8_sequence` with a bumped `version` and use " +
			"`lifecycle { create_before_destroy = true }`. Deleting fails while non-terminal instances still reference the version.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "Sequence version UUID (generated by the provider, UUIDv7).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"tenant_id": schema.StringAttribute{
				Optional: true, Computed: true,
				Description:   "Owning tenant. Defaults to the provider's tenant_id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()},
			},
			"namespace": schema.StringAttribute{
				Optional: true, Computed: true, Default: stringdefault.StaticString("default"),
				Description:   "Namespace. Defaults to `default`.",
				PlanModifiers: replaceStr,
			},
			"name": schema.StringAttribute{
				Required: true, Description: "Sequence name.", PlanModifiers: replaceStr,
			},
			"version": schema.Int64Attribute{
				Required: true, Description: "Sequence version number (unique per tenant/namespace/name).",
				PlanModifiers: []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"definition": schema.StringAttribute{
				CustomType: jsontypes.NormalizedType{},
				Required:   true,
				Description: "JSON object with the sequence body: `blocks` (required) and optionally `input_schema`, `interceptors`, " +
					"`sla`, `on_failure`, `on_cancel`, `schema_version`, `status`. Identity keys (`name`, `namespace`, `tenant_id`, " +
					"`version`) may be present only if they match the attributes; `id`/`created_at` are assigned by the provider. " +
					"Typically `file(\"sequence.json\")` or `jsonencode({...})`.",
				PlanModifiers: replaceStr,
			},
			"status": schema.StringAttribute{
				Computed: true, Description: "Lifecycle status reported by the engine (draft, staging, production, unpublished).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"deprecated": schema.BoolAttribute{
				Computed: true, Description: "Whether this version is deprecated.",
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"created_at": schema.StringAttribute{
				Computed: true, Description: "Creation timestamp (RFC 3339).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"warnings": schema.ListAttribute{
				Computed: true, ElementType: types.StringType,
				Description:   "Lint / template / unknown-field warnings returned by the engine at creation.",
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

// buildSequenceBody merges the definition document with identity attributes.
func buildSequenceBody(m *sequenceModel, tenant, id, createdAt string) (map[string]any, diag.Diagnostics) {
	var diags diag.Diagnostics
	body := map[string]any{}
	if err := json.Unmarshal([]byte(m.Definition.ValueString()), &body); err != nil {
		diags.AddAttributeError(path.Root("definition"), "Invalid definition", "definition must be a JSON object: "+err.Error())
		return nil, diags
	}
	if _, ok := body["blocks"]; !ok {
		diags.AddAttributeError(path.Root("definition"), "Invalid definition", "definition must contain a `blocks` array")
		return nil, diags
	}
	want := map[string]any{
		"tenant_id": tenant,
		"namespace": m.Namespace.ValueString(),
		"name":      m.Name.ValueString(),
		"version":   float64(m.Version.ValueInt64()),
	}
	for k, v := range want {
		if got, ok := body[k]; ok && fmt.Sprint(got) != fmt.Sprint(v) {
			diags.AddAttributeError(path.Root("definition"), "Conflicting definition",
				fmt.Sprintf("definition.%s = %v conflicts with attribute %s = %v; remove it from definition or make them match", k, got, k, v))
		}
	}
	if diags.HasError() {
		return nil, diags
	}
	for k, v := range want {
		body[k] = v
	}
	body["version"] = m.Version.ValueInt64()
	body["id"] = id
	body["created_at"] = createdAt
	return body, diags
}

type sequenceWire struct {
	ID         string `json:"id"`
	TenantID   string `json:"tenant_id"`
	Namespace  string `json:"namespace"`
	Name       string `json:"name"`
	Version    int64  `json:"version"`
	Status     string `json:"status"`
	Deprecated bool   `json:"deprecated"`
	CreatedAt  string `json:"created_at"`
}

func (r *sequenceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan sequenceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	tenant := r.tenantFor(plan.TenantID)
	if !requireTenant(tenant, &resp.Diagnostics) {
		return
	}
	id, err := uuid.NewV7()
	if err != nil {
		resp.Diagnostics.AddError("UUID generation failed", err.Error())
		return
	}
	body, diags := buildSequenceBody(&plan, tenant, id.String(), time.Now().UTC().Format(time.RFC3339Nano))
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	var created struct {
		ID       string   `json:"id"`
		Warnings []string `json:"warnings"`
	}
	if err := r.client.Do(ctx, "POST", "/sequences", nil, body, &created); err != nil {
		addAPIError(&resp.Diagnostics, "create sequence", err)
		return
	}
	if created.ID == "" {
		created.ID = id.String()
	}
	plan.ID = types.StringValue(created.ID)
	plan.TenantID = types.StringValue(tenant)
	warnings, d := types.ListValueFrom(ctx, types.StringType, nonNilStrings(created.Warnings))
	resp.Diagnostics.Append(d...)
	plan.Warnings = warnings
	for _, w := range created.Warnings {
		resp.Diagnostics.AddWarning("Orch8 sequence warning", w)
	}
	found := r.read(ctx, &plan, &resp.Diagnostics)
	if !found && !resp.Diagnostics.HasError() {
		resp.Diagnostics.AddError("Sequence vanished", "sequence was created but could not be read back")
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func nonNilStrings(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

// read refreshes server-owned attributes. The definition itself is not
// rewritten from the server (the engine re-serializes blocks with defaults,
// which would cause spurious replacements); drift in identity fields and
// deletion are detected.
func (r *sequenceResource) read(ctx context.Context, m *sequenceModel, diags *diag.Diagnostics) bool {
	var s sequenceWire
	var raw json.RawMessage
	if err := r.client.Do(ctx, "GET", "/sequences/"+m.ID.ValueString(), nil, nil, &raw); err != nil {
		if isNotFound(err) {
			return false
		}
		addAPIError(diags, "read sequence", err)
		return false
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		diags.AddError("Decode error", err.Error())
		return false
	}
	m.TenantID = types.StringValue(s.TenantID)
	m.Namespace = types.StringValue(s.Namespace)
	m.Name = types.StringValue(s.Name)
	m.Version = types.Int64Value(s.Version)
	m.Status = types.StringValue(s.Status)
	m.Deprecated = types.BoolValue(s.Deprecated)
	m.CreatedAt = types.StringValue(s.CreatedAt)
	if m.Definition.IsNull() || m.Definition.IsUnknown() {
		// Import: seed definition from the server's body without identity keys.
		m.Definition = jsontypes.NewNormalizedValue(stripKeys(raw, append(sequenceIdentityKeys, "deprecated")))
	}
	if m.Warnings.IsNull() || m.Warnings.IsUnknown() {
		m.Warnings = types.ListValueMust(types.StringType, nil)
	}
	return true
}

func stripKeys(raw json.RawMessage, keys []string) string {
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil {
		return string(raw)
	}
	for _, k := range keys {
		delete(obj, k)
	}
	out, _ := json.Marshal(obj)
	return string(out)
}

func (r *sequenceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var st sequenceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &st)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !r.read(ctx, &st, &resp.Diagnostics) {
		if !resp.Diagnostics.HasError() {
			resp.State.RemoveResource(ctx)
		}
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &st)...)
}

func (r *sequenceResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "orch8_sequence versions are immutable; every change forces replacement.")
}

func (r *sequenceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var st sequenceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &st)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Do(ctx, "DELETE", "/sequences/"+st.ID.ValueString(), nil, nil, nil); err != nil && !isNotFound(err) {
		addAPIError(&resp.Diagnostics, "delete sequence", err)
	}
}

func (r *sequenceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
